name: Faturamento Cron

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Permite execução manual

jobs:
  faturamento:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm ci

    - name: Rodar script de faturamento
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        user: ${{ secrets.user }}
        password: ${{ secrets.password }}
      run: node scripts/faturamento.js
